name: "🤖 Agent Run Request"
description: "Solicita al orquestador implementar una historia de usuario (multi-stack / multi-language)."
title: "[AGENT] "
labels: ["agent:run"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Agent Orchestrator
        Completa los datos. Luego, al crear el issue, comenta con:

        ```
        /agent run { ... }
        ```

  - type: input
    id: stack
    attributes:
      label: Stack (libre)
      description: "Ejemplos: python-fastapi-postgres, python-django, java-spring-boot, node-express, dotnet-webapi, go-fiber, react-nextjs, angular."
      placeholder: "p.ej. java-spring-boot"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Lenguaje (libre)
      description: "Escribe el lenguaje que usarás. Ej: python, java, javascript, typescript, csharp, go, kotlin."
      placeholder: "p.ej. java"
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: Historia de usuario
      description: "Formato recomendado: Como <rol> quiero <capacidad> para <beneficio>."
      placeholder: "Como usuario quiero simular un crédito para conocer mi cuota mensual."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Criterios de aceptación
      description: "Uno por línea."
      placeholder: |
        Incluir tests unitarios
        Documentar endpoint / uso
        Manejar casos borde
    validations:
      required: false

  - type: textarea
    id: constraints
    attributes:
      label: Restricciones / políticas
      description: "Uno por línea. Ej: seguir estructura actual, no romper APIs, usar linting, etc."
      placeholder: |
        Seguir estructura actual del repo
        No introducir dependencias no aprobadas
    validations:
      required: false

  - type: input
    id: test_command
    attributes:
      label: Comando de tests
      description: "Ej: pytest -q | npm test | mvn -q test | dotnet test | go test ./..."
      placeholder: "p.ej. mvn -q test"
    validations:
      required: false

  - type: dropdown
    id: max_iterations
    attributes:
      label: Max iterations
      description: "Límite de ciclos implementador⇄tester."
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✅ Comentario para disparar el agente (copia/pega y ajusta)
        > Nota: `language` es libre (texto). `stack` también.
        ```json
        {
          "stack": "<stack>",
          "language": "<language>",
          "user_story": "<historia>",
          "acceptance_criteria": ["<criterio 1>", "<criterio 2>"],
          "constraints": ["<restriccion 1>", "<restriccion 2>"],
          "test_command": "<comando>",
          "max_iterations": 5
        }
        ```
